import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers/providers";
import NavBar from "@/components/common/NavBar";
import Footer from "@/components/common/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "F1Roster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col justify-between items-between bg-gray-950`}
      >
        <Providers>
          <header className="w-full z-50">
            <NavBar />
          </header>
          <main className="flex flex-col w-full mx-auto justify-center items-center z-40">
            {children}
          </main>
          <footer className="w-full z-10">
            <Footer />
          </footer>
        </Providers>
      </body>
    </html>
  );
}
